#!/usr/bin/expect
#!/bin/bash

set timeout 5

set host "localhost"
set port "36331"

spawn telnet $host $port
expect {
	# Provided host and port incorrect
	"telnet: Unable to connect to remote host" {
		puts "[exec tput sgr 0 1][exec tput setaf 1]Error:[exec tput sgr0] [exec tput setaf 3]The provided host|port are not valid. Provided values: Host: $host  |  Port: $port.[exec tput sgr0]"
	}
	# Sucefull login
	"> " {
		send "unpause\r"
		expect {
			"> " {
				send "exit\r"
			}
		}
	}
	# EOF.
	eof {
		send_error "Error: Connection to $host:$port aborted.\n"
	}
	# Connection timeout
	timeout {
		send_error "$test_name: timeout"
	}
}
