#!/usr/bin/expect
#!/bin/bash

log_user 0

# Arguments passed to the script
set argscount [llength $argv]

if {$argscount == 0} {
	puts "[exec tput sgr 0 1][exec tput setaf 3]Usage:[exec tput sgr0] [exec tput bold]fah-cli \[arguments\][exec tput sgr0]"
	puts "[exec tput sgr0 1][exec tput setaf 2]Example:[exec tput sgr0] [exec tput bold]fah-cli pause -- to pause the folding process.[exec tput sgr0]"
	exit 1
}

set timeout 5
set host "localhost"
set port "36330"

proc buildArgs {} {

	set $final_arg [lindex $argv 0]

	for {set i 1} {$i < $argscount} {incr i 1} {
		set $final_arg [$final_arg + " " + [lindex $argv $i]]
	}

	return $final_args
}

spawn telnet $host $port
expect {
	# Provided host and port incorrect
	"telnet: Unable to connect to remote host" {
		puts "[exec tput sgr 0 1][exec tput setaf 1]Error:[exec tput sgr0] [exec tput setaf 3]The provided host|port are not valid. Provided values: Host: $host  |  Port: $port.[exec tput sgr0]"
	}
	# Successfull login
	"> " {
		send -- "[lindex $argv 0]\r"
		expect {
			"> " {
				send -- "exit\r"
				expect {
					eq "Connection closed by foreign host." {
						exit 0
					}
					timeout {
						exit 0
					}
				}
				exit 0
			}
		}
	}
	# EOF error
	eof {
		send_error "Error: Connection to $host:$port aborted.\n"
	}
	# Connection timeout
	timeout {
		send_error "$test_name: timeout"
	}
}
