#!/usr/bin/expect
#!/bin/bash

# Arguments passed to the script
set argscount [llength $argv]

if {$argscount == 0} {
	puts "[exec tput sgr 0 1][exec tput setaf 3]Usage:[exec tput sgr0] [exec tput bold]fah-cli \[arguments\][exec tput sgr0]"
	puts "[exec tput sgr0 1][exec tput setaf 2]Example:[exec tput sgr0] [exec tput bold]fah-cli pause -- to pause the folding process.[exec tput sgr0]"
	exit 1
}

set timeout 5
set host "localhost"
set port "36331"

spawn telnet $host $port
expect {
	# Provided host and port incorrect
	"telnet: Unable to connect to remote host" {
		puts "[exec tput sgr 0 1][exec tput setaf 1]Error:[exec tput sgr0] [exec tput setaf 3]The provided host|port are not valid. Provided values: Host: $host  |  Port: $port.[exec tput sgr0]"
	}
	# Successfull login
	"> " {
		send "unpause\r"
		expect "> " {
			send "exit\r"
		}
	}
	# EOF error
	eof {
		send_error "Error: Connection to $host:$port aborted.\n"
	}
	# Connection timeout
	timeout {
		send_error "$test_name: timeout"
	}
}


